[package]
name = "ruscripter"
version = "0.1.0"
authors = ["Tyler Wickline <twick00@gmail.com>"]
edition = "2018"

[dependencies]
clap = "2.33.0"
serde = {version = "1.0.92", features = ["derive"]}
serde_yaml = "0.8.9"
cursive = "0.12.0"